



<div  class="container">
  <div class="card p-5">
    
    
    <div class="">
    <div class="separator" style="clear: both; text-align: center;">
      
      </div><div><br /></div><p style="text-align: left;">Zawnime Project adalah website streaming video atau koleksi video dari google drive yang telah kami kumpulkan.</p><p style="text-align: left;">Zawnime Project terinspirasi dari situs website streaming sperti samehadaku, oploverz, nanime dan lainnya tapi Zawnime ini saya menambahkan beberapa video tidak cuman anime di zawnime juga terdapat film big movie seperti marvel, venom dan lainnya.</p><h3 style="text-align: left;">Teknologi dalam aplikasi</h3><p style="text-align: left;">Project ini tidak menggunakan CMS seperti blogspot, Wordpress dan lainnya, project ini pure dari codingan sendiri menggunakan PHP.</p><h4 style="text-align: left;">FrontEnd</h4><div><ul style="text-align: left;"><li>HTML</li><li>CSS3</li><li>JavaScript</li><li>Bootstrap</li><li>JQuery</li></ul><h4 style="text-align: left;">BackEnd</h4></div><div><ul style="text-align: left;"><li>PHP</li><li>GoogleApi</li></ul><h4 style="text-align: left;">Hosting Provider</h4></div><div><ul style="text-align: left;"><li>infinityfree</li><li>Hostinger (000webhost)</li></ul><h4 style="text-align: left;">CloudStorage (Penyimpanan video)</h4></div><div><ul style="text-align: left;"><li>Google Drive</li></ul><div><br /></div></div><p style="text-align: left;">Karena project ini tidak mendapatkan dana dari siapapun kami disini memanfaatkan server free dari berbagai provider.</p><h4 style="text-align: left;">Server Link</h4><div><ul style="text-align: left;"><li>Zawnime (FrontEnd) :&nbsp;<a href="https://zawnime.rf.gd">zawnime.rf.gd</a></li><li>ZawApi (BackEnd Server Api data Collection ) :&nbsp;<a href="https://zawapi.000webhostapp.com">zawapi.000webhostapp.com</a></li><li>ZStreamPlayer (Hosting Player, mencegah penculikan link drive) :&nbsp;<a href="http://zstreamplayer.rf.gd/">zstreamplayer.rf.gd/</a></li></ul><div><br /></div></div>
    </div>
    
    <h3 style="text-align: left;">Masalah 1</h3><p>Database  has exceeded the 'max_queries_per_hour'</p><div class="separator" style="clear: both; text-align: center;"><a href="https://c.tenor.com/cJRcMyUAiMcAAAAd/ah-shit-here-we-go-again-ah-shit.gif" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="336" class="img-fluid" data-original-width="518" height="336" src="https://c.tenor.com/cJRcMyUAiMcAAAAd/ah-shit-here-we-go-again-ah-shit.gif" width="518" /></a></div><div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEihV4CvRWYALax0QZDVOqRoysY9JVZ_9BY2LI2DG4maSlYybBv_DoFZY7h9gf3cygv_tOyoTgnFhK6SF5ftHdMDqS7DpVr69zBSQWJ_3_E1zvt15AA0XBciOA77mI7I2u9aX44maUPRBm_ChgvQnEWxXa_6MJ9PhDxlAYQJVSGr25K1jhKbrszWp-Tu/s363/captures_chrome-capture-2022-6-30.png" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="142" data-original-width="363" class="img-fluid" height="125" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEihV4CvRWYALax0QZDVOqRoysY9JVZ_9BY2LI2DG4maSlYybBv_DoFZY7h9gf3cygv_tOyoTgnFhK6SF5ftHdMDqS7DpVr69zBSQWJ_3_E1zvt15AA0XBciOA77mI7I2u9aX44maUPRBm_ChgvQnEWxXa_6MJ9PhDxlAYQJVSGr25K1jhKbrszWp-Tu/s320/captures_chrome-capture-2022-6-30.png" width="320" /></a></div><p style="text-align: left;">Disebabkan ini database/server gratis :(, yaa jadi setiap request ke database dibatasi 1.5k per jam, untuk menyelesaikan permasalahan ini saya jadi membuat dua database dan mengimport data yang ada di database 1dan kebalikannya jika database 2 melebihi database query, untuk 1 jam sekali.</p><p style="text-align: left;">Karena saya membuat fitur lookup dimana setiap halaman di load akan query ke database dengan berisikan ip pengunjung dan text dump yang berisikin dimana pengunjung melihat/menonton video apa dan episode berapa atau server apa, fitur ini saya buat untuk melihat trafik dari website.</p><p style="text-align: left;"></p><blockquote>Atau bisa jadi ini serangan DDOS attack yang sangat benci ke website saya :(, pesan : jangan lah begitu bambang, disini saya cuman mempublikasikan video yang telah saya koleksi dari berbagai web, jika anda tidak suka dengan web zawnime tidakusahlah anda mengirim request begituan, lagian ini server gratis juga ga ada untungnya anda menyerang website saya :(.</blockquote><p></p>
    
  </div>
</div>

 